#!/bin/sh

close() {
    local result="$(todoist list | fzf --tac --height 20)"
    [ -n "$result" ] \
        && (
            local id="$(echo $result | awk '{print $1}')"
            gum spin todoist close $id --title="Closing task..." --show-error \
                && echo "Task closed!"
        ) || true
}

case $1 in
    "close" | "c")
        close
        ;;
    *)
        echo "subcomand \`$1\` not found"
        ;;
esac
