#!/bin/sh

get_task() {
    todoist list | fzf --tac --height 20
}

show() {
    local result="$(get_task)"
    [ -n "$result" ] \
        && (
            echo $result | awk '{print $1}' | xargs todoist show
        ) || true
}

modify() {
    local result="$(get_task)"
    [ -n "$result" ] \
        && (
            local id="$(echo $result | awk '{print $1}')"
            local selection="$(gum choose \
                "content" \
                "priority" \
                "project" \
                "date")"
            case $selection in
                "content")
                    todoist show $id \
                        | awk '{if($1 == "Content") print}' \
                        | sed 's/Content  //' \
                        | gum write \
                        | xargs -I {} todoist m -c {} $id
                    ;;
                "priority")
                    todoist show $id \
                        | awk '{if($1 == "Priority") print}' \
                        | sed 's/Priority //' | sed 's/p//' \
                        | xargs -I {} gum choose 1 2 3 4 --header="Current Priority: {}" \
                        | xargs -I {} todoist m -p {} $id || true
                    ;;
                *) echo todo ;;
            esac
        ) || true
}

close() {
    local result="$(get_task)"
    [ -n "$result" ] \
        && (
            local id="$(echo $result | awk '{print $1}')"
            gum spin todoist close $id --title="Closing task..." --show-error \
                && echo "Task closed!"
        ) || true
}

delete() {
    local result="$(get_task)"
    [ -n "$result" ] \
        && (
            local id="$(echo $result | awk '{print $1}')"
            gum spin todoist delete $id --title="Deleting task..." --show-error \
                && echo "Task deleted!"
        ) || true
}

case $1 in
    "show") show ;;
    "modify" | "m") modify ;;
    "close" | "c") close ;;
    "delete" | "d") delete ;;
    "quick" | "q") gum spin todoist "$@" --title="Creating task..." ;;
    *) todoist "$@" ;;
esac
